### ISSUE TITLE
[Bug] LMAX value for minimum_functional_level dropped

### ISSUE THREAD

**Issue by SLemonier** [citrix/terraform-provider-citrix#155] opened 2024-11-14 13:56 UTC
Hello guys

## Describe the bug
Last time I used this provider, minimum_functional_level accepted value LMAX for a machine catalog.
This is no longer the case and it answers:
│ Attribute minimum_functional_level value must be one of: ["L5" "L7" "L7_6" "L7_7" "L7_8" "L7_9" "L7_20" "L7_25" "L7_30" "L7_34"], got: "LMAX"

**Terraform command (import, apply, etc):** terraform plan
**Resource impacted:** machine catalog creation

## Versions

*Use the `terraform -v` command to find the Terraform and Citrix Provider versions.*
**Terraform:** latest
**citrix/citrix provider:** latest 

## Terraform configuration files
*Paste or attach any relevant `.tf` files with secrets and identifying information removed.*

## Terraform console output
*Paste the output from Terraform CLI including any errors and the transactionIds if present.*
│ Attribute minimum_functional_level value must be one of: ["L5" "L7" "L7_6" "L7_7" "L7_8" "L7_9" "L7_20" "L7_25" "L7_30" "L7_34"], got: "LMAX"

**Comment by AlanCitrix** [comment] 2024-11-14 17:29
In order to fix #64 we decided to remove support for LMIN/LMAX and require explicit functional level selection. Apologies this should have been marked as a breaking change in the 0.6.0 release notes.

The reason we removed it was because it creates ambiguous behavior in an IaC world. Does LMAX in your Terraform plan mean:
1. Create this machine catalog/delivery group with the current max functional level and keep it there until I change it or
2. Keep this catalog/delivery group at the max functional level. When a new functional level is released the next Terraform plan would flag the change

Option 1 creates issues because when reviewing TF files you don't know which functional version each catalog is one. It would appear they are at the same version.

Option 2 would cause a machine catalog to be marked for change in a `plan` even though the user may not be touching the catalog, which could create confusion. This is especially an issue in cloud DaaS because the new version is released without any notification, but even for on-premises customers this could catch someone by surprise.

Can you provide more information about what you are trying to accomplish, or what you think the expected behavior should be if LMAX is specified?

**Comment by SLemonier** [comment] 2024-11-15 09:28
Hello Alan

Thought about this issue as well.

I wanted to use the latest functional level but it's not the way terraform is supposed to handle such type of settings.
I don't know if this property is really relevant though. I mean, it is for old version (7.6) because of policies and some mechanisms, but for recent versions, never saw any impact.

Maybe worth to discuss internally about the relevance of this and close this github bug.

**Closed** 2024-11-15 16:03 UTC
Labels: bug
